name: CI

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup dotnet
        id: setup-dotnet
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: src/global.json

      - name: Set base name
        id: base-name
        run: |
          if ('${{ github.ref_type }}' -eq 'tag')
          {
            $value = 'UserRights-x64-${{ github.ref_name }}'
          }
          else
          {
            $value = 'UserRights-x64'
          }

          'value={0}' -f $value |Tee-Object -FilePath $env:GITHUB_OUTPUT -Append

      - name: Run CLI tests
        run: |
          cd .\src
          dotnet.exe test --project .\Tests.Cli\Tests.Cli.csproj --configuration Debug --runtime win-x64 --output Detailed

      - name: Run Application tests
        run: |
          cd .\src
          dotnet.exe test --project .\Tests.Application\Tests.Application.csproj --configuration Debug --runtime win-x64 --output Detailed

      - name: Clean solution
        run: |
          cd .\src
          dotnet.exe clean .\UserRights.slnx

      - name: Publish framework-dependent release
        run: |
          cd .\src
          dotnet.exe publish .\UserRights\UserRights.csproj --configuration Release --runtime win-x64 --no-self-contained --output .\publish-fdd

      - name: Archive framework-dependent release
        run: |
          cd .\src\publish-fdd
          Get-ChildItem . -Exclude *.pdb,*.xml -Recurse |Compress-Archive -DestinationPath .\${{ steps.base-name.outputs.value }}.zip

      - name: Upload framework-dependent release
        uses: actions/upload-artifact@v7
        with:
            name: ${{ steps.base-name.outputs.value }}
            path: ./src/publish-fdd
            if-no-files-found: error

      - name: Clean solution
        run: |
          cd .\src
          dotnet.exe clean .\UserRights.slnx

      - name: Publish self-contained release
        run: |
          cd .\src
          dotnet.exe publish .\UserRights\UserRights.csproj --configuration Release --runtime win-x64 --self-contained --output .\publish-scd -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:EnableCompressionInSingleFile=true

      - name: Archive self-contained release
        run: |
          cd .\src\publish-scd
          Compress-Archive -Path ./UserRights.exe -DestinationPath .\${{ steps.base-name.outputs.value }}-self-contained.zip

      - name: Upload self-contained release
        uses: actions/upload-artifact@v7
        with:
            name: ${{ steps.base-name.outputs.value }}-self-contained
            path: ./src/publish-scd
            if-no-files-found: error

      - name: Publish release
        if: github.ref_type == 'tag'
        run: |
          @'
          # Windows User Rights Assignment Utility

          Compiled with .NET SDK ${{ steps.setup-dotnet.outputs.dotnet-version }}

          ## ${{ steps.base-name.outputs.value }}-self-contained.zip

          Self-contained release for Windows x64

          ## ${{ steps.base-name.outputs.value }}.zip

          Framework-dependent release for Windows x64
          '@ |gh.exe release create ${{ github.ref_name }} --verify-tag --title ${{ github.ref_name }} --notes-file - .\src\publish-fdd\${{ steps.base-name.outputs.value }}.zip .\src\publish-scd\${{ steps.base-name.outputs.value }}-self-contained.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
